# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'caffeNetViewer.ui'
#
# Created: Wed May 10 08:42:11 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(601, 737)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.layoutWidget = QtGui.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 9, 521, 101))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.comboBoxModel = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxModel.sizePolicy().hasHeightForWidth())
        self.comboBoxModel.setSizePolicy(sizePolicy)
        self.comboBoxModel.setEditable(True)
        self.comboBoxModel.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.comboBoxModel.setObjectName("comboBoxModel")
        self.horizontalLayout.addWidget(self.comboBoxModel)
        self.toolButtonModel = QtGui.QToolButton(self.layoutWidget)
        self.toolButtonModel.setObjectName("toolButtonModel")
        self.horizontalLayout.addWidget(self.toolButtonModel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.comboBoxWeights = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxWeights.sizePolicy().hasHeightForWidth())
        self.comboBoxWeights.setSizePolicy(sizePolicy)
        self.comboBoxWeights.setEditable(True)
        self.comboBoxWeights.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.comboBoxWeights.setObjectName("comboBoxWeights")
        self.horizontalLayout_2.addWidget(self.comboBoxWeights)
        self.toolButtonWeights = QtGui.QToolButton(self.layoutWidget)
        self.toolButtonWeights.setObjectName("toolButtonWeights")
        self.horizontalLayout_2.addWidget(self.toolButtonWeights)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.comboBoxImage = QtGui.QComboBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxImage.sizePolicy().hasHeightForWidth())
        self.comboBoxImage.setSizePolicy(sizePolicy)
        self.comboBoxImage.setEditable(True)
        self.comboBoxImage.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.comboBoxImage.setObjectName("comboBoxImage")
        self.horizontalLayout_3.addWidget(self.comboBoxImage)
        self.toolButtonImage = QtGui.QToolButton(self.layoutWidget)
        self.toolButtonImage.setObjectName("toolButtonImage")
        self.horizontalLayout_3.addWidget(self.toolButtonImage)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.pushButtonExec = QtGui.QPushButton(Dialog)
        self.pushButtonExec.setGeometry(QtCore.QRect(540, 50, 51, 51))
        self.pushButtonExec.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/exec.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonExec.setIcon(icon)
        self.pushButtonExec.setIconSize(QtCore.QSize(48, 48))
        self.pushButtonExec.setObjectName("pushButtonExec")
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 120, 581, 611))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.layoutWidget1 = QtGui.QWidget(self.tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 10, 511, 22))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.comboBoxLayers = QtGui.QComboBox(self.layoutWidget1)
        self.comboBoxLayers.setObjectName("comboBoxLayers")
        self.horizontalLayout_4.addWidget(self.comboBoxLayers)
        self.layoutWidget2 = QtGui.QWidget(self.tab)
        self.layoutWidget2.setGeometry(QtCore.QRect(30, 40, 231, 22))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtGui.QLabel(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.comboBoxOutType = QtGui.QComboBox(self.layoutWidget2)
        self.comboBoxOutType.setObjectName("comboBoxOutType")
        self.comboBoxOutType.addItem("")
        self.comboBoxOutType.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBoxOutType)
        self.labelDisplay = QtGui.QLabel(self.tab)
        self.labelDisplay.setGeometry(QtCore.QRect(30, 70, 512, 512))
        self.labelDisplay.setFrameShape(QtGui.QFrame.Box)
        self.labelDisplay.setText("")
        self.labelDisplay.setObjectName("labelDisplay")
        self.layoutWidget_2 = QtGui.QWidget(self.tab)
        self.layoutWidget_2.setGeometry(QtCore.QRect(280, 40, 261, 22))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtGui.QLabel(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.comboBoxChannel = QtGui.QComboBox(self.layoutWidget_2)
        self.comboBoxChannel.setObjectName("comboBoxChannel")
        self.horizontalLayout_7.addWidget(self.comboBoxChannel)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.plainTextEdit = QtGui.QPlainTextEdit(self.tab_2)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 10, 561, 571))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Caffe Net Viewer  ( WawLabs ) ", None, QtGui.QApplication.UnicodeUTF8))
        Dialog.setWhatsThis(QtGui.QApplication.translate("Dialog", "<html><head/><body><p>Deneme</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Model Name (*.prtotxt)", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonModel.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Weights Name (*.caffemodel)", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonWeights.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Input Image Name ", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonImage.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Layer Name :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Output Type", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxOutType.setItemText(0, QtGui.QApplication.translate("Dialog", "Blob", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxOutType.setItemText(1, QtGui.QApplication.translate("Dialog", "Weights", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Channel", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Dialog", "Graphical", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Dialog", "Text", None, QtGui.QApplication.UnicodeUTF8))

